# Apache
PHPMYADMIN_SERVER_ADMIN: webmaster@example.org
PHPMYADMIN_SERVER_PATH: /phpmyadmin

# Self signed certificat will be generated
# if PHPMYADMIN_HTTPS is set to true and no certificat and key are provided.

# To use your custom certificat and key 2 options :
# - add them in service/phpmyadmin/assets/apache2/ssl and build the image
# - or during docker run mount a data volume with those files to /container/service/phpmyadmin/apache2/ssl
PHPMYADMIN_HTTPS: true
PHPMYADMIN_HTTPS_CRT_FILENAME: phpmyadmin.crt
PHPMYADMIN_HTTPS_KEY_FILENAME: phpmyadmin.key
PHPMYADMIN_HTTPS_CA_CRT_FILENAME: ca.crt

PHPMYADMIN_TRUST_PROXY_SSL: false

PHPMYADMIN_SSL_HELPER_PREFIX: phpmyadmin
